name: "Release Pipeline"
on:
  push:
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v2 #v2: v2.3.4 available
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1.2.0 #v1: V1.2.0 available
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1 #v1
      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v2 #note: newer is available
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/adrian-testorg/juice-shop-image:${{ steps.tag.outputs.tag }}
